name: Scheduled Terraform Apply
run-name: Scheduled Terraform Apply

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

  terraform-apply:
    name: "Terraform apply"
    needs: [setup]
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      apply: true
